import type { Metadata } from "next";

import "../globals.css";
import { Navbar } from "./_components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MarketingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` h-full`}>
        <Navbar />
        <main className="pt-40 pb-20 "> {children} </main>
      </body>
    </html>
  );
}
